export const SITE_TITLE_HOME = 'Home - Jane Goodreads | Author'
export const SITE_DESCRIPTION = '#1 New Yorks Times Bestselling Author'
export const SITE_TITLE_ABOUT = 'About - Jane Goodreads | Author'
export const SITE_TITLE_CONTACT = 'Contact - Jane Goodreads | Author'
export const SITE_TITLE_EVENTS = 'Events - Jane Goodreads | Author'
export const SITE_TITLE_BOOKS = 'Books - Jane Goodreads | Author'
